### ISSUE TITLE
class类的疑惑

### ISSUE THREAD

**Issue by lepture** [aralejs/class#3]
by @zero7u  seajs/modules#20

class 模块的 class-debug.js 49 行，SubClass 里面可否加一句代码：

``` javascript
this.superclass = parent.prototype;
```

这样的话，在子类的方法里面就可以通过 this.superclass 调用父类的方法，而不是通过类名，因为类名可能会改动的。

``` javascript
var Person = Class.create({
  name: 'zero',
  getInfo: function() {
    return this.name;
  }
});
var Black = Person.extend({
  initialize: ...,
  color: 'black',
  getInfo: function() {
    // 这里如果可以写成：
    // this.superclass.getInfo() + this.color;
    // 这样，实际代码就不和类名耦合了
    return Black.superclass.getInfo() + this.color;
  }
});
```

不知道设计时是否有其他想法，希望得到指点，谢谢！

**Comment by lifesinger** [comment]
这个初衷是不想污染 instance，以及增加这层语法糖，带来的性价比不高，比如如果不想与类名耦合，可以简单写成：

``` js
this.constructor.superclass
```

这样就解耦了。更进一步的做法是提供 `this.parent()` 方法，像 MooTools 一样，但这也是看起来舒服了，却留下了一些陷阱，还不如简单提供 superclass 来得简单明白。

可以参见文档：https://github.com/aralejs/class/blob/master/docs/competitors.md
