### ISSUE TITLE
性能对比的那个链接里 seajs 的链接返回 404 了。

### ISSUE THREAD

**Issue by cisolarix** [aralejs/class#4]
可以借鉴 jQuery 用 latest 来做路径，而不是 1.1.0 之类的版本号。
http://jsperf.com/class-perfs  <--链接

**Comment by cisolarix** [comment]
转眼一个月之前了啊？

**Comment by popomore** [comment]
恩，latest 可以考虑，@lifesinger 先把这个链接改下吧

**Comment by lifesinger** [comment]
不能直接修改原来的

可以看这个： http://jsperf.com/class-perfs/8
