### ISSUE TITLE
代码优化缩短，能少几个字符就是几个啊~

### ISSUE THREAD

**Issue by nuintun** [aralejs/class#6]
``` javascript
var isArray = Array.isArray

if (!isArray) {
  isArray = function(val) {
    return toString.call(val) === '[object Array]'
  }
}
```

修改成：

``` javascript
var isArray = Array.isArray || function(val) {
  return toString.call(val) === '[object Array]'
}
```

像这种代码感觉能用短路做法就用短路呗~

**Comment by lifesinger** [comment]
感谢，这个的确可以优化

On Thu, Mar 28, 2013 at 9:44 AM, NewtonNiu notifications@github.com wrote:

> var isArray = Array.isArray
> if (!isArray) {
>   isArray = function(val) {
>     return toString.call(val) === '[object Array]'
>   }}
> 
> 修改成：
> 
> var isArray = Array.isArray || function(val) {
>   return toString.call(val) === '[object Array]'}
> 
> 像这种代码感觉能用短路做法就用短路呗~
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/aralejs/class/issues/6
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香
